#!/bin/bash

BASE_DIR=/home/stdnt

function echo_error {
    echo -e "\033[91mERR:\033[0m $1"
    return 0
}

function echo_progress {
    echo -e "\033[94mProgress:\033[0m $1"
    return 0
}

# Abort if non-root user
if [ "$(id -u)" -ne 0 ]; then
    echo_error "A \033[1mroot privilege\033[0m is required to run this script." >&2
    exit 1
fi

if [[ "$(getent group stdnt)" =~ stdnt:x:([0-9]+): ]]; then
    STDNT_GID=${BASH_REMATCH[1]}
else
    echo_error "Student group does not exist." >&2
    exit 1
fi

getent passwd | while IFS=: read -r USER_NAME USER_PASS USER_UID USER_GID USER_GECOS USER_HOME USER_SHELL; do
    if [ "$STDNT_GID" == "$USER_GID" ]; then
        echo "Deleting user $USER_NAME"
        deluser "$USER_NAME"
        rm -rf "$USER_HOME"
    fi
done
