#!/bin/bash

function echo_error {
    echo -e "\033[91mERR:\033[0m $1"
    return 0
}

if [ -z "$1" ]; then
    echo_error "Provide \033[1mta usernames list\033[0m file path."
    exit 1
fi

INPUT_FILE_PATH=$1

if ! [ -f "$INPUT_FILE_PATH" ]; then
    echo_error "File \033[1m$INPUT_FILE_PATH\033[0m does not exist."
    exit 1
fi

OUTPUT_FILE_PATH="tmp/$(basename $INPUT_FILE_PATH | sed s/\.txt/.secret.txt/)"

touch $OUTPUT_FILE_PATH

cat $INPUT_FILE_PATH | while read USERNAME; do
    if [[ "$USERNAME" =~ ^[a-z0-9-]+$ ]]; then
        SECRET=$(echo "$USERNAME $(date)" | sha256sum | cut -c1-32)
        echo -e "$USERNAME,$SECRET" >> $OUTPUT_FILE_PATH
    else
        echo_error "Invalid username \033[4m$USERNAME\033[0m detected. Skipping..."
        echo -e "" >> $OUTPUT_FILE_PATH
    fi
done
