#!/bin/bash

SHARED_DIR=/ca25
TARBALL_URL=https://github.com/B-Lang-org/bsc/releases/download/2024.07/bsc-2024.07-ubuntu-20.04.tar.gz

TARBALL_BASENAME=$(basename $TARBALL_URL)
BSC_DIRNAME=$(echo $TARBALL_BASENAME | sed s/\.tar\.gz//)

function echo_error {
    echo -e "\033[91mERR:\033[0m $1"
    return 0
}

function echo_progress {
    echo -e "\033[94mProgress:\033[0m $1"
    return 0
}

# Abort if non-root user
if [ "$(id -u)" -ne 0 ]; then
    echo_error "A \033[1mroot privilege\033[0m is required to run this script." >&2
    exit 1
fi

echo_progress "Download and extract bsc compiler"
mkdir -p tmp/
wget -O tmp/$TARBALL_BASENAME $TARBALL_URL
tar -zxvf tmp/$TARBALL_BASENAME -C tmp/

echo_progress "Move bsc compiler to the shared directory"
mkdir -p $SHARED_DIR/bsc
cp -r -t $SHARED_DIR/bsc tmp/$BSC_DIRNAME/*
chown -R ca-admin:ca-admin $SHARED_DIR

echo_progress "Add shared bsc dir to the global path"
echo "" >> /etc/profile
echo "if [ -d $SHARED_DIR/bsc/bin ]; then" >> /etc/profile
echo "  PATH=\"$SHARED_DIR/bsc/bin:\$PATH\"" >> /etc/profile
echo "fi" >> /etc/profile

echo_progress "Install necessary packages"
apt install -y gcc g++ make tree tcl
